aboutus/urls.py
from django import urls
from django.urls import path
from . import views

app_name = 'aboutus'

urlpatterns = [

    path("",views.aboutus,name= 'about')

]

blog/urls.py
from django.urls import path
from . import views

app_name= "blog"


urlpatterns = [

    path('',views.blog_list,name ='blogs'),
    path('<int:id>/',views.blog_detail,name = 'detail'),
    path('tag/<slug:tag>',views.blog_tag, name = 'tag'),
    path('category/<slug:categorys>',views.blog_category, name = 'category'),
    path('search/',views.search, name = 'search')
    
]

myproject/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('works.urls')),
    path('reservation/',include('reservation.urls')),
    path('blog/',include('blog.urls')),
    path('contact/',include('contact.urls')),
    path('users/',include('users.urls')),
    path("aboutus/", include('aboutus.urls')),
]

urlpatterns += static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

users/urls.py
from reservation.models import reservation
from django.urls import path
from . import views
from reservation.views import reservations

app_name = 'users'

urlpatterns = [
    
    path('',views.signup_view,name = 'signup'),
    path('login',views.login_view,name = 'login'),
    path('logout',views.LogoutUser,name = 'logout'),
    path(r'reservation/',reservations,name='reservations'),
    path('user/',views.user_views,name='userviews')
]

works/urls.py
from django.urls import path, re_path
from . import views
from reservation.views import reservations
from blog.views import blog_list
from contact.views import contact

app_name = 'works'

urlpatterns = [

    path(r'',views.works_list,name='works_list'),
    path(r'reservation/',reservations,name='reservations'),
    path(r'blog/',blog_list,name='blog'),
    path(r'contact/',contact,name='contact_url')
] 

templates/partials/_footer.html
{% load static %}
    <footer class="footer-area bg-f">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-6 js-cnt">
					{% for about_content in about %}
					<h3>در باره ما</h3>
					<p>{{about_content.summary | truncatewords:49}}</p>
					{% endfor %}
				</div>
				<div class="col-lg-3 col-md-6">
					<h3>ساعت های کاری</h3>
					<p><span class="text-color">شنبه تا پنج شنبه :</span> ۹ - ۱۸</p>
				</div>
				<div class="col-lg-3 col-md-6">
					<h3>اطلاعات تماس</h3>
					<p class="lead">خیابان لورم, ساختمان لورم, پلاک ۵</p>
					<p>m.esmaili.se@gmail.com</p>
				</div>
				<div class="col-lg-3 col-md-6">
					<ul class="list-inline f-social">
					{% for about_contact in about %}
						{% for about_contacts in about_contact.links.all %}
						<li class="list-inline-item"><a href="{{about_contacts.Acounturl}}"><i class="{{about_contacts.icons}}" aria-hidden="true"></i></a></li>
						<li class="list-inline-item"><a href="{{about_contacts.Acounturl}}"><i class="f2c6" aria-hidden="true"></i></a></li>				
						{% endfor %}
					{% endfor %}
					</ul>
				</div>
			</div>
		</div>
	</footer>

templates/partials/_header.html
{% load static %}
	<header class="top-navbar">
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<div class="container">
				<a class="navbar-brand" href="{% url 'works:works_list' %}">
					<img class="logo-image" src="{%static 'images/logo.png' %}" alt="logo"  />
				</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars-rs-food" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
				  <span class="navbar-toggler-icon"></span>
				</button>
				{% with url_name=request.resolver_match.url_name %}
				<div class="collapse navbar-collapse direction" id="navbars-rs-food">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item {% if url_name == 'works_list' %}active{% endif %}"><a class="nav-link" href="{% url 'works:works_list' %}">خانه</a></li>
						<li class="nav-item {% if url_name == 'about' %}active{% endif %}"><a class="nav-link" href="{% url 'aboutus:about' %}">درباره ما</a></li>
						<li class="nav-item dropdown {% if url_name == 'reservations' %}active{% endif %}">
							<a class="nav-link dropdown-toggle " href="#" id="dropdown-a" data-toggle="dropdown">صفحات</a>
							<div class="dropdown-menu direction" aria-labelledby="dropdown-a">
								<a class="dropdown-item" href="{% url 'works:reservations' %}">رزرو</a>
								<a class="dropdown-item" href="{% url 'works:works_list' %}">گالری</a>
							</div>
						</li>
						<li class="nav-item {% if url_name == 'blog' %}active{% endif %}"><a class="nav-link" href="{% url 'works:blog' %}">وب لاگ</a></li>
						<li class="nav-item {% if url_name == 'contact_url' %}active{% endif %}"><a class="nav-link" href="{% url 'works:contact_url' %}">ارتباط با ما</a></li>

						{% if user.is_authenticated %}
							<li class="nav-item dropdown ">
								<a class="nav-link dropdown-toggle " href="#" id="dropdown-a" data-toggle="dropdown">{{user.username}}</a>
								<div class="dropdown-menu direction" aria-labelledby="dropdown-a">
									<a class="dropdown-item" href="{% url 'users:userviews' %}">پروفایل</a>
									<form action='{% url 'users:logout' %}' method='POST'>{% csrf_token %}<button type='submit' class="dropdown-item">خروج</form>									
								</div>
							</li>
							{% else %}
								<li class="nav-item {% if url_name == 'login' %}active{% endif %}"><a class="nav-link" href="{% url 'users:login' %}">ورود به سایت</a></li>
						{% endif %}
						
					</ul>
				</div>
				{% endwith %}
			</div>
		</nav>
	</header>