aboutus/urls.py
from django import urls
from django.urls import path
from . import views

app_name = 'aboutus'

urlpatterns = [

    path("",views.aboutus,name= 'about')

]

blog/urls.py
from django.urls import path
from . import views

app_name= "blog"


urlpatterns = [

    path('',views.blog_list,name ='blogs'),
    path('<int:id>/',views.blog_detail,name = 'detail'),
    path('tag/<slug:tag>',views.blog_tag, name = 'tag'),
    path('category/<slug:categorys>',views.blog_category, name = 'category'),
    path('search/',views.search, name = 'search')
    
]

myproject/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('works.urls')),
    path('reservation/',include('reservation.urls')),
    path('blog/',include('blog.urls')),
    path('contact/',include('contact.urls')),
    path('users/',include('users.urls')),
    path("aboutus/", include('aboutus.urls')),
]

urlpatterns += static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

reservation/urls.py
from django.urls import path
from . import views
app_name='reservation'

urlpatterns = [
    path('',views.reservations,name = 'reservationview'),
    
]

    

aboutus/models.py
from typing import Text
from django.db import models
from django.utils.translation import gettext as _
from ckeditor.fields import RichTextField
from django.utils import timezone
# Create your models here.

class AboutUs(models.Model):
    Title = models.CharField(_("عنوان"), max_length=200)
    summary = models.TextField(_("خلاصه درباره ما"))
    content = RichTextField(_("محتوا درباره"))
    photo = models.ImageField(_("عکس"), upload_to='aboutus/',)
    links  = models.ManyToManyField("LinkAcount", verbose_name=_("رسانه ها"))
    created_at = models.DateTimeField(_("زمان انتشار"),default=timezone.now)

    class Meta:
        verbose_name = 'درباره ما'
        verbose_name_plural = 'درباره ما'    

    def __str__(self):
        return self.Title

class LinkAcount(models.Model):
    choose =(
        ('fa fa-facebook', 'فیس بوک'),
        ('fa fa-twitter', 'توییتر'),
        ('fa fa-linkedin', 'لینک دین'),
        ('fa fa-google-plus', 'گوگل پلاس'),
        ('fa fa-instagram', 'اینستا گرام'),
        ('fa fa-whatsapp', 'واتس اپ'),     
    )
    name = models.CharField(_("نام رسانه"), max_length=50)
    Acounturl = models.URLField(_("ادرس رسانه"), max_length=200)
    icons = models.CharField(_("انتخاب شمایل"), choices=choose,max_length=200)

    class Meta:
        verbose_name = 'رسانه  اجتماعی'
        verbose_name_plural = 'رسانه های اجتماعی'    

    def __str__(self):
        return self.name

aboutus/views.py
from django.shortcuts import render
from .models import AboutUs
from works.models import works,Category
# Create your views here.
def aboutus(request):
    about = AboutUs.objects.all()
    works_list = works.objects.all()
    category = Category.objects.all()
    contex={
        "about":about,
        'works' : works_list, 
        'category' : category,
    }

    return render(request, 'aboutus/about.html',contex)

aboutus/templates/aboutus/about.html
{% extends 'masterpage.html' %}
{% block title %}درباره ما{% endblock title %}

{% block content %}

	<!-- Start All Pages -->
	<div class="all-page-title page-breadcrumb">
		<div class="container text-center">
			<div class="row">
				<div class="col-lg-12">
					<h1>بلاگ</h1>
				</div>
			</div>
		</div>
	</div>
	<!-- End All Pages -->

	<!-- Start About -->
	{% for abouts in about %}
	<div class="about-section-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-6">
					<img src="{{abouts.photo.url}}" alt="" class="img-fluid">
				</div>
				<div class="col-lg-6 col-md-6 text-center">
					<div class="inner-column">
						
						<h1>خوش آمیدید به<span> {{abouts.Title}}</span></h1>
						
						<h4>یک داستان کوچک</h4>

						<p>{{abouts.summary}}</p>

						<a class="btn btn-lg btn-circle btn-outline-new-white" href="{% url 'reservation:reservationview' %}">درخواست کار</a>
					</div>
				</div>
				<div class="col-md-12">
					<div class="inner-pt details-page">
						{{abouts.content|safe}}
					</div>
				</div>
			</div>
		</div>
	</div>
	{% endfor %}
	<!-- End About -->
	
	<!-- Start Menu -->
	<div class="menu-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="heading-title text-center">
						<h2>نمونه کار های ما</h2>
						<p>شما میتوانید از دکمه های زیر کار های مارا مشاهد کنید</p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12">
					<div class="special-menu text-center">
						<div class="button-group filter-button-group direction">
						<button class="active" data-filter="*">همه موارد</button>
							{% for categorys in category %}
							<button data-filter=".{{categorys.name_work_en}}">{{categorys.name_work_fa}}</button>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
				
			<div class="row special-list">
				{% for work in works %}
				
				<div class="col-lg-4 col-md-6 special-grid {{work.category.name_work_en}}">
					<div class="gallery-single fix">
						<img src="{{work.photo.url}}" class="img-fluid2" alt="Image">
						<div class="why-text direction">
							
							<h4>{{work.category.name_work_fa}}</h4>
							<p>{{work.description}}</p>
							<h5>تومان : {{work.price}}</h5>
						</div>
					</div>
				</div>
				</a>
				{% endfor %}

				
			</div>
		</div>
	</div>
	<!-- End Menu -->

	
{% endblock content %}