blog/urls.py
from django.urls import path
from . import views

app_name= "blog"


urlpatterns = [

    path('',views.blog_list,name ='blogs'),
    path('<int:id>/',views.blog_detail,name = 'detail'),
    path('tag/<slug:tag>',views.blog_tag, name = 'tag'),
    path('category/<slug:categorys>',views.blog_category, name = 'category'),
    path('search/',views.search, name = 'search')
    
]

myproject/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('works.urls')),
    path('reservation/',include('reservation.urls')),
    path('blog/',include('blog.urls')),
    path('contact/',include('contact.urls')),
    path('users/',include('users.urls')),
    path("aboutus/", include('aboutus.urls')),
]

urlpatterns += static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

users/urls.py
from reservation.models import reservation
from django.urls import path
from . import views
from reservation.views import reservations

app_name = 'users'

urlpatterns = [
    
    path('',views.signup_view,name = 'signup'),
    path('login',views.login_view,name = 'login'),
    path('logout',views.LogoutUser,name = 'logout'),
    path(r'reservation/',reservations,name='reservations'),
    path('user/',views.user_views,name='userviews')
]

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.translation import gettext as _
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

class Blog(models.Model):
    title = models.CharField(_("عنوان"),max_length = 150)
    description = models.CharField(_("توضیحات"),max_length = 150)
    content = RichTextField()
    created_at = models.DateTimeField(_("زمان انتشار"),default=timezone.now)
    author = models.ForeignKey(User,verbose_name=_("نویسنده"),on_delete = models.CASCADE)
    image = models.ImageField(_("تصویر"),upload_to="blogs/",)
    category = models.ForeignKey("Category", on_delete=models.CASCADE,verbose_name=_("دسته بندی"),related_name="blog")
    tags = models.ManyToManyField("Tag",verbose_name=_("تگ ها"),related_name = "blogs")

    class Meta:
        verbose_name = 'بلاگ'
        verbose_name_plural = 'بلاگ ها'

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(_("عنوان"),max_length = 150)
    slug = models.SlugField(_("عنوان لاتین"))
    published_at = models.DateField(_("تاریخ انتشار"),auto_now=False,auto_now_add=True)

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'    

    def __str__(self):
        return self.title

class Tag(models.Model):
    title = models.CharField(_("عنوان"),max_length=50)
    slug = models.SlugField(_("عنوان لاتین"))
    published_at = models.DateTimeField(_("تاریخ انتشار"),auto_now=False,auto_now_add=True)
    update_at = models.DateTimeField(_("تاریخ بروز رسانی"), auto_now=True,auto_now_add=False)

    class Meta:
        verbose_name = 'تگ'
        verbose_name_plural = 'تگ ها' 

    def __str__(self):
        return self.title


class Comment(models.Model):
    name = models.CharField(_("نام کاربر"), max_length=50)
    email = models.EmailField(_("ادرس الکترونیکی"),max_length=254)
    message = models.TextField(_("متن مورد نظر"))
    data = models.DateField(_("تاریخ انتشار"),auto_now= False,auto_now_add = True)
    blog = models.ForeignKey("Blog", on_delete=models.CASCADE,verbose_name=_("مقاله"),related_name="comments")

    class Meta:
        verbose_name = 'کامنت'
        verbose_name_plural = 'کامنت ها' 

    def __str__(self):
        return self.email
    

    

blog/forms.py
from django import forms

class CommentForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField(max_length=254)
    message = forms.CharField(widget =forms.Textarea)

blog/views.py
from django.shortcuts import render , redirect , HttpResponseRedirect
from django.urls import reverse 
from .models import Blog ,Tag ,Category , Comment
from .forms import CommentForm
from django.contrib import messages
from django.core.paginator import Paginator
# Create your views here.


def blog_list(request):
    
    blogs = Blog.objects.all()
    paginator = Paginator(blogs, 3)
    page_number  = request.GET.get('page')
    blog_obj = paginator.get_page(page_number)
    
    contex={
        "blog_obj":blog_obj
    }

    return render(request, "blog/blog_list.html",contex)

def blog_detail(request,id):

    
    blog = Blog.objects.get(id = id)
    tags = Tag.objects.all().filter(blogs = blog)
    recents = Blog.objects.all().order_by("-created_at")[:5]
    categories = Category.objects.all()
    comments = Comment.objects.all().filter(blog = blog)

    
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            new_name = form.cleaned_data['name']
            new_email = form.cleaned_data['email']
            new_message = form.cleaned_data['message']

            new_comment = Comment(blog=blog,name=new_name,email=new_email,message=new_message)
            new_comment.save()
            messages.success(request, 'با موفقیت ثبت شد ')
            return HttpResponseRedirect(reverse('blog:detail', kwargs = {'id':id}))
            
                        
    else:
        form = CommentForm()
        

    contex ={
        "blog":blog,
        "tags":tags,
        "recents":recents,
        "categories":categories,
        "comments":comments,
         
    }

    return render(request,"blog/blog_detail.html",contex)



def blog_tag(request,tag):
    blogs = Blog.objects.filter(tags__slug = tag)

    paginator = Paginator(blogs, 3)
    page_number  = request.GET.get('page')
    blog_obj = paginator.get_page(page_number)
    
    contex={
        "blog_obj":blog_obj
    }

    return render(request, "blog/blog_list.html",contex)



def blog_category(request,categorys):
    
    blogs = Blog.objects.filter(category__slug = categorys)

    paginator = Paginator(blogs, 3)
    page_number  = request.GET.get('page')
    blog_obj = paginator.get_page(page_number)

    contex = {
        "blog_obj":blog_obj
    }

    return render(request, "blog/blog_list.html",contex)

def search (request):
    
    if request.method == 'GET':
        q = request.GET.get("search")

    blog_search = Blog.objects.filter(title__icontains = q)

    paginator = Paginator(blog_search, 3)
    page_number  = request.GET.get('page')
    blog_obj = paginator.get_page(page_number) 

    return render(request,"blog/blog_list.html",{"blog_obj":blog_obj})
    
    

blog/templates/blog/blog_detail.html
{% extends 'masterpage.html' %}
{% load static %}
{% block title %}{{blog.title}}{% endblock title %}
{% block blog %}active{% endblock blog %}

{% block content %}

	<!-- Start All Pages -->
	<div class="all-page-title page-breadcrumb">
		<div class="container text-center">
			<div class="row">
				<div class="col-lg-12">
					<h1>بلاگ</h1>
				</div>
			</div>
		</div>
	</div>
	<!-- End All Pages -->
	
	<!-- Start blog details -->
	<div class="blog-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="heading-title text-center">
						<h2>{{blog.title}}</h2>
						<p>{{blog.description}}</p>
						
						{% if messages %}
						{% for message in messages %}
							<div class="alert alert-success">{{message}}</div>
						{% endfor %}
						{% endif %}
						
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-xl-8 col-lg-8 col-12">
					<div class="blog-inner-details-page">
						<div class="blog-inner-box">
							<div class="side-blog-img">
								<img class="img-fluid3" src="{{blog.image.url}}" alt="">							
								<div class="date-blog-up">
									{{blog.created_at|date:"y b"}}
								</div>
							</div>
							<div class="inner-blog-detail details-page">
								<h3>{{blog.description}}</h3>
								<ul class="align-list">
									<li><i class="zmdi zmdi-account"></i>ارسال توسط : <span>{{blog.author.first_name}} {{blog.author.last_name}}</span></li>
									<li>|</li>
									<li><i class="zmdi zmdi-time "></i>زمان : <span class="time-blog">{{blog.created_at|time}}</span></li>
								</ul>
								<p>{{blog.content|safe}}</p>
						
							</div>
						</div>

						<div class="blog-comment-box">
							<h3>دیدگاه دیگران</h3>
                           {% for cm in comments %} 
                                    <div class="comment-item" > 
                                        <div class="comment-item-right">
                                            <div class="pull-left">
                                                {{cm.name}}
                                            </div>
                                            <div class="pull-right">
                                                <i class="fa fa-calendar-o" aria-hidden="true"></i><span>{{cm.data}}</span> : تاریخ
                                            </div>
                                            <div class="des-l">
                                                <p class="direction">{{cm.message}}</p>
                                            </div>
                                            
                                        </div>
                                    </div>
                           {% endfor %}
						</div>

						<div class="comment-respond-box mb-5">
							<h3>دیدگاهتان را بنویسید</h3>
							<div class="comment-respond-form">
								<form  method="POST" id="commentrespondform" class="comment-form-respond row">
									{% csrf_token %}
									<div class="col-lg-6-comment col-md-6 col-sm-6">
										<div class="form-group">
											<input id="name" class="form-control" name="name" placeholder="نام" type="text">
										</div>
										<div class="form-group">
											<input id="email" class="form-control" name="email" placeholder="ایمیل" type="email">
										</div>
									</div>
									<div class="col-lg-6-comment col-md-6 col-sm-6">
										<div class="form-group">
											<textarea class="form-control"  name="message" id="message" placeholder="متن شما" rows="2"></textarea>
										</div>
									</div>
									<div class="col-lg-12 col-md-12 col-sm-12 direction">
									{% if user.is_authenticated %}
										
											<button class="btn btn-submit" type="submit">ثبت دیدگاه</button>
										
									{% else %}
										<span>لطفا ابتدا <a href='{% url 'users:login' %}'>وارد</a> حساب کاربری خود شوید یا حساب کاربری <a href='{% url 'users:signup' %}'>بسازید.</a></span>
									{% endif %}
									</div>
								</form>
							</div>
						</div>

					</div>
				</div>
				
				<div class="col-xl-4 col-lg-4 col-md-6 col-sm-8 col-12 blog-sidebar direction">
					<div class="right-side-blog">
						<h3>جوست و جو</h3>
							<form method="GET" action="{% url 'blog:search' %}">
								<div class="blog-search-form">
									<input name="search" placeholder="جست و جو مقالات" type="text">
									<button class="search-btn" type="submit">
										<i class="fa fa-search" aria-hidden="true"></i>
									</button>
								</div>
							</form>
						<h3>دسته بندی ها</h3>
						<div class="blog-categories">
							<ul>
                                {% for  category in categories  %}
								<li><a href="{% url 'blog:category' category.slug %}"><span>{{category.title}}</span></a></li>
                                {% endfor %}
							</ul>
						</div>
						<h3>پست های اخیر</h3>
						<div class="post-box-blog">
							{% for blog in recents  %}
                                <div class="recent-post-box">
								<div class="recent-box-blog">
									<div class="recent-img">
										<img class="img-fluid-recent" src="{{blog.image.url}}" alt="" >
									</div>								
									<div class="recent-info">
										<ul>
											<li><i class="zmdi zmdi-account"></i>ارسال توسط : <span>{{blog.author.first_name}} {{blog.author.last_name}}</span></li>
											<li>|</li>
											<li><i class="zmdi zmdi-time"></i>زمان : <span class="time-blog">{{blog.created_at|time}}</span></li>
										</ul>
										<h4><a href ="{% url 'blog:detail' blog.id %}">{{blog.description}}</a></h4>
									</div>
								</div>
							</div>
                            {% endfor %}
						</div>
						<h3>تگ های اخیر</h3>
						<div class="blog-tag-box">
							<ul class="list-inline tag-list">
                                {% for tag in tags %}
								<li class="list-inline-item"><a href="{% url 'blog:tag' tag.slug %}">{{tag.title}}</a></li>
                                {% endfor %}
							</ul>
						</div>
					</div>
				</div>
			
			</div>
		</div>
	</div>
	<!-- End details -->


{% endblock content %}

blog/templates/blog/blog_list.html
{% extends 'masterpage.html' %}
{% load static %}

{% block title %}بلاگ ها{% endblock title %}

{% block content %}

	<!-- Start All Pages -->
	<div class="all-page-title page-breadcrumb">
		<div class="container text-center">
			<div class="row">
				<div class="col-lg-12">
					<h1>بلاگ ها</h1>
				</div>
			</div>
		</div>
	</div>
	<!-- End All Pages -->
	
	<!-- Start blog -->
	<div class="blog-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="heading-title text-center">
						<h2>بلاگ ها</h2>
						<p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.</p>
					</div>
				</div>
			</div>
			<div class="row">

				{% for blog in blog_obj  %}	
					<div class="col-lg-4 col-md-6 col-12">
						<div class="blog-box-inner">
							<div class="blog-img-box">
								<img class="img-fluid" src="{{blog.image.url}}" style="height:420px;" alt="">
							</div>
							<div class="blog-detail">
								<h4>{{blog.title}}</h4>
								<ul>
									<li><span>ارسال توسط {{blog.author}}</span></li>
									<li>|</li>
									<li><span>{{blog.created_at|date:"Y b d"}}</span></li>
								</ul>
								
								<p dir="rtl">{{blog.content|truncatewords:60|safe}}</p>
								<a class="btn btn-lg btn-circle btn-outline-new-white" href="{% url 'blog:detail' blog.id %}">بیشتر</a>
							</div>
						</div>
					</div>
				{% endfor %}

			</div>
		</div>
	</div>
	<!-- End blog -->

	<!--Start Paginator-->
	{% if blog_obj.has_other_pages %}
		<div class= "container mb-3">
			<div class="row">
				<div class="col d-flex justify-content-center">
				
					<nav aria-label="Page navigation example">
						<ul class="pagination">
						{% if blog_obj.has_previous %}
						<li class="page-item"><a class="page-link" href="?page={{blog_obj.paginator.first_pages}}">اولین</a></li>
							<li class="page-item">
							<a class="page-link" href="?page=1" aria-label="Previous">
								<span aria-hidden="true">&laquo;</span>
								<span class="sr-only">Previous</span>
							</a>
							</li>
			
						{% endif %}

						{% for page in blog_obj.paginator.page_range %}

							{% if blog_obj.number == page %}

							<li class="page-item active"><a class="page-link" href="?page={{page}}">{{page}}</a></li>

							{% else %}
							<li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>

							{% endif %}
							
							
						{% endfor %}


						{% if blog_obj.has_next %}
							<li class="page-item">
							<a class="page-link" href="?page={{blog_obj.next_page_number}}" aria-label="Next">
								<span aria-hidden="true">&raquo;</span>
								<span class="sr-only">Next</span>
							</a>
							</li>
							<li class="page-item"><a class="page-link" href="?page={{blog_obj.paginator.num_pages}}">آخرین</a></li>
						{% endif %}
						</ul>
					</nav>

				</div>
			</div>
		</div>

	{% endif %}
	<!--End Paginator-->


{% endblock content %}